//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageToMidi.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImageToMidi.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Adding Image: 的本地化字符串。
        /// </summary>
        public static string B_AddImage {
            get {
                return ResourceManager.GetString("B_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Files 的本地化字符串。
        /// </summary>
        public static string B_AllFiles {
            get {
                return ResourceManager.GetString("B_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back.. 的本地化字符串。
        /// </summary>
        public static string B_Back {
            get {
                return ResourceManager.GetString("B_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Converting to MIDI: 的本地化字符串。
        /// </summary>
        public static string B_ConvertingMidi {
            get {
                return ResourceManager.GetString("B_ConvertingMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export All MIDIs 的本地化字符串。
        /// </summary>
        public static string B_ExportAllMidi {
            get {
                return ResourceManager.GetString("B_ExportAllMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting Video Frames: 的本地化字符串。
        /// </summary>
        public static string B_ExtractingVideoFrames {
            get {
                return ResourceManager.GetString("B_ExtractingVideoFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FFmpeg Exporting Complete 的本地化字符串。
        /// </summary>
        public static string B_FFmpegCompleted {
            get {
                return ResourceManager.GetString("B_FFmpegCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image/Video 的本地化字符串。
        /// </summary>
        public static string B_FileFormat {
            get {
                return ResourceManager.GetString("B_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        public static string B_FolderFormat {
            get {
                return ResourceManager.GetString("B_FolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Completed 的本地化字符串。
        /// </summary>
        public static string B_MergeCompleted {
            get {
                return ResourceManager.GetString("B_MergeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Into One MIDI 的本地化字符串。
        /// </summary>
        public static string B_MergeMidi {
            get {
                return ResourceManager.GetString("B_MergeMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Starting FFmpeg... 的本地化字符串。
        /// </summary>
        public static string B_StartingFFmpeg {
            get {
                return ResourceManager.GetString("B_StartingFFmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch Processing 的本地化字符串。
        /// </summary>
        public static string B_Title {
            get {
                return ResourceManager.GetString("B_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filename 的本地化字符串。
        /// </summary>
        public static string BDG_FileName {
            get {
                return ResourceManager.GetString("BDG_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format 的本地化字符串。
        /// </summary>
        public static string BDG_Format {
            get {
                return ResourceManager.GetString("BDG_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames 的本地化字符串。
        /// </summary>
        public static string BDG_FrameCount {
            get {
                return ResourceManager.GetString("BDG_FrameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        public static string BDG_Index {
            get {
                return ResourceManager.GetString("BDG_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resolution 的本地化字符串。
        /// </summary>
        public static string BDG_Resolution {
            get {
                return ResourceManager.GetString("BDG_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CIEDE2000 的本地化字符串。
        /// </summary>
        public static string CA_CIEDE2000 {
            get {
                return ResourceManager.GetString("CA_CIEDE2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HSL 的本地化字符串。
        /// </summary>
        public static string CA_HSL {
            get {
                return ResourceManager.GetString("CA_HSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HSV 的本地化字符串。
        /// </summary>
        public static string CA_HSV {
            get {
                return ResourceManager.GetString("CA_HSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LAB 的本地化字符串。
        /// </summary>
        public static string CA_LAB {
            get {
                return ResourceManager.GetString("CA_LAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RGB 的本地化字符串。
        /// </summary>
        public static string CA_RGB {
            get {
                return ResourceManager.GetString("CA_RGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clustering Method 的本地化字符串。
        /// </summary>
        public static string ClusteringMethod {
            get {
                return ResourceManager.GetString("ClusteringMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBSCAN (Good for few colors) 的本地化字符串。
        /// </summary>
        public static string CM_DBSCAN {
            get {
                return ResourceManager.GetString("CM_DBSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Density-based clustering that can discover arbitrarily shaped clusters. 的本地化字符串。
        /// </summary>
        public static string CM_DBSCAN_ToolTip {
            get {
                return ResourceManager.GetString("CM_DBSCAN_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed Palette 的本地化字符串。
        /// </summary>
        public static string CM_FixedBitPalette {
            get {
                return ResourceManager.GetString("CM_FixedBitPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uses fixed palette, up to 256 colors. 的本地化字符串。
        /// </summary>
        public static string CM_FixedBitPalette_ToolTip {
            get {
                return ResourceManager.GetString("CM_FixedBitPalette_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Floyd–Steinberg Dithering 的本地化字符串。
        /// </summary>
        public static string CM_FloydSteinberg {
            get {
                return ResourceManager.GetString("CM_FloydSteinberg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classic error diffusion dithering algorithm, improves color representation. 的本地化字符串。
        /// </summary>
        public static string CM_FloydSteinberg_ToolTip {
            get {
                return ResourceManager.GetString("CM_FloydSteinberg_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaussian Mixture 的本地化字符串。
        /// </summary>
        public static string CM_GMM {
            get {
                return ResourceManager.GetString("CM_GMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaussian mixture model, suitable for images with multi-Gaussian color distributions. 的本地化字符串。
        /// </summary>
        public static string CM_GMM_ToolTip {
            get {
                return ResourceManager.GetString("CM_GMM_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hierarchical Clustering 的本地化字符串。
        /// </summary>
        public static string CM_Hierarchical {
            get {
                return ResourceManager.GetString("CM_Hierarchical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bottom-up cluster merging, forming hierarchical structures. 的本地化字符串。
        /// </summary>
        public static string CM_Hierarchical_ToolTip {
            get {
                return ResourceManager.GetString("CM_Hierarchical_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans++ (Default) 的本地化字符串。
        /// </summary>
        public static string CM_KMeansPP_Default {
            get {
                return ResourceManager.GetString("CM_KMeansPP_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans++ clustering with improved initial point selection for more stable clustering results. 的本地化字符串。
        /// </summary>
        public static string CM_KMeansPP_ToolTip {
            get {
                return ResourceManager.GetString("CM_KMeansPP_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KM++ &amp; KM (Recommended) 的本地化字符串。
        /// </summary>
        public static string CM_KMPlusKM_Recommended {
            get {
                return ResourceManager.GetString("CM_KMPlusKM_Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Has randomness] KMeans++ initialization + KMeans clustering, improves clustering quality. 的本地化字符串。
        /// </summary>
        public static string CM_KMPlusKM_Recommended_ToolTip {
            get {
                return ResourceManager.GetString("CM_KMPlusKM_Recommended_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lab KMeans 的本地化字符串。
        /// </summary>
        public static string CM_LabKMeans {
            get {
                return ResourceManager.GetString("CM_LabKMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans clustering in Lab color space, more consistent with human visual perception. 的本地化字符串。
        /// </summary>
        public static string CM_LabKMeans_ToolTip {
            get {
                return ResourceManager.GetString("CM_LabKMeans_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MeanShift (Good for few colors) 的本地化字符串。
        /// </summary>
        public static string CM_MeanShift {
            get {
                return ResourceManager.GetString("CM_MeanShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mean shift clustering, no need to specify cluster count, suitable for complex distributions. 的本地化字符串。
        /// </summary>
        public static string CM_MeanShift_ToolTip {
            get {
                return ResourceManager.GetString("CM_MeanShift_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MinMax &amp; KM++ 的本地化字符串。
        /// </summary>
        public static string CM_MinMaxKM {
            get {
                return ResourceManager.GetString("CM_MinMaxKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min-max distance method combined with KMeans++, improves clustering diversity. 的本地化字符串。
        /// </summary>
        public static string CM_MinMaxKM_ToolTip {
            get {
                return ResourceManager.GetString("CM_MinMaxKM_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arduano Native KM 的本地化字符串。
        /// </summary>
        public static string CM_NativeKM {
            get {
                return ResourceManager.GetString("CM_NativeKM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Arduano&apos;s native KMeans algorithm, the same algorithm used in the original ImageToMidi. 的本地化字符串。
        /// </summary>
        public static string CM_NativeKM_ToolTip {
            get {
                return ResourceManager.GetString("CM_NativeKM_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Octree 的本地化字符串。
        /// </summary>
        public static string CM_Octree {
            get {
                return ResourceManager.GetString("CM_Octree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Octree space partitioning, suitable for images with sparse color distribution. 的本地化字符串。
        /// </summary>
        public static string CM_Octree_ToolTip {
            get {
                return ResourceManager.GetString("CM_Octree_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OPTICS (Good for few colors) 的本地化字符串。
        /// </summary>
        public static string CM_OPTICS {
            get {
                return ResourceManager.GetString("CM_OPTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Density-based clustering algorithm that can discover cluster structures of different densities. 的本地化字符串。
        /// </summary>
        public static string CM_OPTICS_ToolTip {
            get {
                return ResourceManager.GetString("CM_OPTICS_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordered Dithering 的本地化字符串。
        /// </summary>
        public static string CM_OrderedDither {
            get {
                return ResourceManager.GetString("CM_OrderedDither", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ordered dithering using Bayer matrix, suitable for low color depth displays. 的本地化字符串。
        /// </summary>
        public static string CM_OrderedDither_ToolTip {
            get {
                return ResourceManager.GetString("CM_OrderedDither_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCA Principal Component (Good for few colors) 的本地化字符串。
        /// </summary>
        public static string CM_PCA {
            get {
                return ResourceManager.GetString("CM_PCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Principal component analysis, extracts the main direction of color distribution. 的本地化字符串。
        /// </summary>
        public static string CM_PCA_ToolTip {
            get {
                return ResourceManager.GetString("CM_PCA_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frequency Method 的本地化字符串。
        /// </summary>
        public static string CM_Popularity {
            get {
                return ResourceManager.GetString("CM_Popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selects dominant colors by frequency of appearance, simple and efficient. 的本地化字符串。
        /// </summary>
        public static string CM_Popularity_ToolTip {
            get {
                return ResourceManager.GetString("CM_Popularity_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spectral Clustering 的本地化字符串。
        /// </summary>
        public static string CM_Spectral {
            get {
                return ResourceManager.GetString("CM_Spectral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graph theory-based clustering method, suitable for complex structures. 的本地化字符串。
        /// </summary>
        public static string CM_Spectral_ToolTip {
            get {
                return ResourceManager.GetString("CM_Spectral_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Variance Split 的本地化字符串。
        /// </summary>
        public static string CM_VarianceSplit {
            get {
                return ResourceManager.GetString("CM_VarianceSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Splits along the direction of maximum color variance, highlighting dominant colors. 的本地化字符串。
        /// </summary>
        public static string CM_VarianceSplit_ToolTip {
            get {
                return ResourceManager.GetString("CM_VarianceSplit_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF + K-Means 的本地化字符串。
        /// </summary>
        public static string CM_WpfKMeans {
            get {
                return ResourceManager.GetString("CM_WpfKMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Has randomness] Uses WPF median cut first, then K-Means for refinement, balancing speed and quality. 的本地化字符串。
        /// </summary>
        public static string CM_WpfKMeans_ToolTip {
            get {
                return ResourceManager.GetString("CM_WpfKMeans_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF Median Cut (Native) 的本地化字符串。
        /// </summary>
        public static string CM_WpfMedianCut {
            get {
                return ResourceManager.GetString("CM_WpfMedianCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF&apos;s built-in median cut algorithm, fast and suitable for simple scenarios. 的本地化字符串。
        /// </summary>
        public static string CM_WpfMedianCut_ToolTip {
            get {
                return ResourceManager.GetString("CM_WpfMedianCut_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Allocation 的本地化字符串。
        /// </summary>
        public static string ColorAllocation {
            get {
                return ResourceManager.GetString("ColorAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color Count 的本地化字符串。
        /// </summary>
        public static string ColorCount {
            get {
                return ResourceManager.GetString("ColorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Auto Colors 的本地化字符串。
        /// </summary>
        public static string ColorEventsSelect {
            get {
                return ResourceManager.GetString("ColorEventsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview Color Seed 的本地化字符串。
        /// </summary>
        public static string ColorSeed {
            get {
                return ResourceManager.GetString("ColorSeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click the image on the left or type the hex below to pick a color 的本地化字符串。
        /// </summary>
        public static string ColPickerTip {
            get {
                return ResourceManager.GetString("ColPickerTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Color Selected 的本地化字符串。
        /// </summary>
        public static string CP_NoColorSelected {
            get {
                return ResourceManager.GetString("CP_NoColorSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Decoding Completed 的本地化字符串。
        /// </summary>
        public static string CS_DecodingCompleted {
            get {
                return ResourceManager.GetString("CS_DecodingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export successful! 的本地化字符串。
        /// </summary>
        public static string CS_ExportingCompleted {
            get {
                return ResourceManager.GetString("CS_ExportingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export successful! Click to open the folder 的本地化字符串。
        /// </summary>
        public static string CS_ExportingFolder {
            get {
                return ResourceManager.GetString("CS_ExportingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exporting MIDI... 的本地化字符串。
        /// </summary>
        public static string CS_ExportingMidi {
            get {
                return ResourceManager.GetString("CS_ExportingMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export MIDI ( 的本地化字符串。
        /// </summary>
        public static string CS_ExportNotecount1 {
            get {
                return ResourceManager.GetString("CS_ExportNotecount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notes ) 的本地化字符串。
        /// </summary>
        public static string CS_ExportNotecount2 {
            get {
                return ResourceManager.GetString("CS_ExportNotecount2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Image... 的本地化字符串。
        /// </summary>
        public static string CS_GeneratingImage {
            get {
                return ResourceManager.GetString("CS_GeneratingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Landscape Thumbnails 的本地化字符串。
        /// </summary>
        public static string CS_GeneratingLandscape {
            get {
                return ResourceManager.GetString("CS_GeneratingLandscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Notes... 的本地化字符串。
        /// </summary>
        public static string CS_GeneratingNotes {
            get {
                return ResourceManager.GetString("CS_GeneratingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Palette... 的本地化字符串。
        /// </summary>
        public static string CS_GeneratingPalette {
            get {
                return ResourceManager.GetString("CS_GeneratingPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generating Portrait Thumbnails 的本地化字符串。
        /// </summary>
        public static string CS_GeneratingPortrait {
            get {
                return ResourceManager.GetString("CS_GeneratingPortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/4 Analyzing BoundingBox 的本地化字符串。
        /// </summary>
        public static string CS_GSBoundingBox {
            get {
                return ResourceManager.GetString("CS_GSBoundingBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3/4 Reading PNG Results... 的本地化字符串。
        /// </summary>
        public static string CS_GSReading {
            get {
                return ResourceManager.GetString("CS_GSReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2/4 Rendering With Ghostscript... 的本地化字符串。
        /// </summary>
        public static string CS_GSRendering {
            get {
                return ResourceManager.GetString("CS_GSRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4/4 Scaling Completed 的本地化字符串。
        /// </summary>
        public static string CS_GSScaling {
            get {
                return ResourceManager.GetString("CS_GSScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keys 的本地化字符串。
        /// </summary>
        public static string CS_Keys {
            get {
                return ResourceManager.GetString("CS_Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black(Clipped) 的本地化字符串。
        /// </summary>
        public static string CS_KeysBlackClipped {
            get {
                return ResourceManager.GetString("CS_KeysBlackClipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black(Filled) 的本地化字符串。
        /// </summary>
        public static string CS_KeysBlackFilled {
            get {
                return ResourceManager.GetString("CS_KeysBlackFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Black(Fixed) 的本地化字符串。
        /// </summary>
        public static string CS_KeysBlackFixed {
            get {
                return ResourceManager.GetString("CS_KeysBlackFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White(Clipped) 的本地化字符串。
        /// </summary>
        public static string CS_KeysWhiteClipped {
            get {
                return ResourceManager.GetString("CS_KeysWhiteClipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White(Filled) 的本地化字符串。
        /// </summary>
        public static string CS_KeysWhiteFilled {
            get {
                return ResourceManager.GetString("CS_KeysWhiteFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 White(Fixed) 的本地化字符串。
        /// </summary>
        public static string CS_KeysWhiteFixed {
            get {
                return ResourceManager.GetString("CS_KeysWhiteFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading File... 的本地化字符串。
        /// </summary>
        public static string CS_LoadingFile {
            get {
                return ResourceManager.GetString("CS_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI File 的本地化字符串。
        /// </summary>
        public static string CS_MidiFile {
            get {
                return ResourceManager.GetString("CS_MidiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bitmap/Vector Image 的本地化字符串。
        /// </summary>
        public static string CS_OpenFilter {
            get {
                return ResourceManager.GetString("CS_OpenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait... 的本地化字符串。
        /// </summary>
        public static string CS_PleaseWait {
            get {
                return ResourceManager.GetString("CS_PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/3 Analyzing SVG... 的本地化字符串。
        /// </summary>
        public static string CS_SVGAnalyzing {
            get {
                return ResourceManager.GetString("CS_SVGAnalyzing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SVG Thumbnail Generation Completed 的本地化字符串。
        /// </summary>
        public static string CS_SVGCompleted {
            get {
                return ResourceManager.GetString("CS_SVGCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3/3 Converting To WPF Bitmap... 的本地化字符串。
        /// </summary>
        public static string CS_SVGConverting {
            get {
                return ResourceManager.GetString("CS_SVGConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2/3 Rendering SVG... 的本地化字符串。
        /// </summary>
        public static string CS_SVGRendering {
            get {
                return ResourceManager.GetString("CS_SVGRendering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thumbnail Generation Completed 的本地化字符串。
        /// </summary>
        public static string CS_ThumbGenCompleted {
            get {
                return ResourceManager.GetString("CS_ThumbGenCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HEX: 的本地化字符串。
        /// </summary>
        public static string CS_TrackHex {
            get {
                return ResourceManager.GetString("CS_TrackHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Note Count: 的本地化字符串。
        /// </summary>
        public static string CS_TrackNoteCount {
            get {
                return ResourceManager.GetString("CS_TrackNoteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid hex RGB color 的本地化字符串。
        /// </summary>
        public static string ErrorTextBlock {
            get {
                return ResourceManager.GetString("ErrorTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate Color Events 的本地化字符串。
        /// </summary>
        public static string GenColorEvents {
            get {
                return ResourceManager.GetString("GenColorEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Height 的本地化字符串。
        /// </summary>
        public static string HM_CustomHeight {
            get {
                return ResourceManager.GetString("HM_CustomHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Aspect Ratio 的本地化字符串。
        /// </summary>
        public static string HM_OriginalAspectRatio {
            get {
                return ResourceManager.GetString("HM_OriginalAspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original Pixel Height 的本地化字符串。
        /// </summary>
        public static string HM_OriginalHeight {
            get {
                return ResourceManager.GetString("HM_OriginalHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same As Width 的本地化字符串。
        /// </summary>
        public static string HM_SameAsWidth {
            get {
                return ResourceManager.GetString("HM_SameAsWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Height 的本地化字符串。
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Previewing 的本地化字符串。
        /// </summary>
        public static string ImagePreviewing {
            get {
                return ResourceManager.GetString("ImagePreviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interpolation Method 的本地化字符串。
        /// </summary>
        public static string InterpolationMethod {
            get {
                return ResourceManager.GetString("InterpolationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key Range 的本地化字符串。
        /// </summary>
        public static string KeyRange {
            get {
                return ResourceManager.GetString("KeyRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limited Note Length 的本地化字符串。
        /// </summary>
        public static string LimitedLength {
            get {
                return ResourceManager.GetString("LimitedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No files to export. 的本地化字符串。
        /// </summary>
        public static string M_NoFilesToExport {
            get {
                return ResourceManager.GetString("M_NoFilesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI BPM 的本地化字符串。
        /// </summary>
        public static string MidiBpm {
            get {
                return ResourceManager.GetString("MidiBpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Output 的本地化字符串。
        /// </summary>
        public static string MidiOutput {
            get {
                return ResourceManager.GetString("MidiOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI PPQ 的本地化字符串。
        /// </summary>
        public static string MidiPpq {
            get {
                return ResourceManager.GetString("MidiPpq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MIDI Previewing 的本地化字符串。
        /// </summary>
        public static string MidiPreviewing {
            get {
                return ResourceManager.GetString("MidiPreviewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start of the Notes 的本地化字符串。
        /// </summary>
        public static string NL_FlowWithColor {
            get {
                return ResourceManager.GetString("NL_FlowWithColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start of the Image 的本地化字符串。
        /// </summary>
        public static string NL_SplitToGrid {
            get {
                return ResourceManager.GetString("NL_SplitToGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlimited 的本地化字符串。
        /// </summary>
        public static string NL_Unlimited {
            get {
                return ResourceManager.GetString("NL_Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Average Linkage 的本地化字符串。
        /// </summary>
        public static string PP_AverageLinkage {
            get {
                return ResourceManager.GetString("PP_AverageLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merges clusters with closest average distance each time, compromise solution. 的本地化字符串。
        /// </summary>
        public static string PP_AverageLinkage_ToolTip {
            get {
                return ResourceManager.GetString("PP_AverageLinkage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bandwidth (bandwidth) 的本地化字符串。
        /// </summary>
        public static string PP_Bandwidth {
            get {
                return ResourceManager.GetString("PP_Bandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bandwidth parameter for mean shift. Decimal. Recommended 16~64. Lower values produce finer clustering, higher values produce coarser clustering. 的本地化字符串。
        /// </summary>
        public static string PP_Bandwidth_ToolTip {
            get {
                return ResourceManager.GetString("PP_Bandwidth_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Base Palette Algorithm 的本地化字符串。
        /// </summary>
        public static string PP_BaseMethod {
            get {
                return ResourceManager.GetString("PP_BaseMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bit Depth (bit depth) 的本地化字符串。
        /// </summary>
        public static string PP_BitDepth {
            get {
                return ResourceManager.GetString("PP_BitDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Overrides the color count setting above, generates a fixed bit depth palette. Color count is 2 to the power of bit depth. 的本地化字符串。
        /// </summary>
        public static string PP_BitDepth_ToolTip {
            get {
                return ResourceManager.GetString("PP_BitDepth_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete Linkage 的本地化字符串。
        /// </summary>
        public static string PP_CompleteLinkage {
            get {
                return ResourceManager.GetString("PP_CompleteLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merges farthest clusters each time, produces compact clusters, noise resistant. 的本地化字符串。
        /// </summary>
        public static string PP_CompleteLinkage_ToolTip {
            get {
                return ResourceManager.GetString("PP_CompleteLinkage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DBSCAN 的本地化字符串。
        /// </summary>
        public static string PP_DBSCAN {
            get {
                return ResourceManager.GetString("PP_DBSCAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 2000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_DBSCANMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_DBSCANMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance Type (distance) 的本地化字符串。
        /// </summary>
        public static string PP_Distance {
            get {
                return ResourceManager.GetString("PP_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Distance metric for clustering. Euclidean distance: commonly used, suitable for continuous data; Manhattan distance: suitable for discrete data. 的本地化字符串。
        /// </summary>
        public static string PP_Distance_ToolTip {
            get {
                return ResourceManager.GetString("PP_Distance_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dither Strength (0.0~2.0) 的本地化字符串。
        /// </summary>
        public static string PP_DitherStrength {
            get {
                return ResourceManager.GetString("PP_DitherStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neighborhood Radius (epsilon) 的本地化字符串。
        /// </summary>
        public static string PP_Epsilon {
            get {
                return ResourceManager.GetString("PP_Epsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neighborhood radius for DBSCAN clustering. Decimal. Recommended 1~10. Lower values produce finer clustering, higher values produce coarser clustering. 的本地化字符串。
        /// </summary>
        public static string PP_Epsilon_ToolTip {
            get {
                return ResourceManager.GetString("PP_Epsilon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Euclidean Distance 的本地化字符串。
        /// </summary>
        public static string PP_EuclideanDistance {
            get {
                return ResourceManager.GetString("PP_EuclideanDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commonly used distance, suitable for continuous data. 的本地化字符串。
        /// </summary>
        public static string PP_EuclideanDistance_ToolTip {
            get {
                return ResourceManager.GetString("PP_EuclideanDistance_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the algorithm for generating the base palette. Different algorithms affect color distribution and speed. 的本地化字符串。
        /// </summary>
        public static string PP_FloydBaseMethod_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydBaseMethod_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suitable for complex color distributions. 的本地化字符串。
        /// </summary>
        public static string PP_FloydDBSCAN_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydDBSCAN_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dither error diffusion strength. Decimal. Recommended 1.0. Lower values produce weaker dithering, higher values produce stronger dithering, too high may cause excessive noise. 的本地化字符串。
        /// </summary>
        public static string PP_FloydDitherStrength_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydDitherStrength_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Better clustering results, slightly slower speed. 的本地化字符串。
        /// </summary>
        public static string PP_FloydKMeansPP_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydKMeansPP_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suitable for images with distinct dominant colors. 的本地化字符串。
        /// </summary>
        public static string PP_FloydPCA_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydPCA_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When enabled, dithering scan direction alternates each row, reducing stripe artifacts. Recommended to enable. 的本地化字符串。
        /// </summary>
        public static string PP_FloydSerpentine_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydSerpentine_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Balances speed and quality. 的本地化字符串。
        /// </summary>
        public static string PP_FloydWpfKMeans_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydWpfKMeans_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fast, suitable for simple images. 的本地化字符串。
        /// </summary>
        public static string PP_FloydWpfMedianCut_ToolTip {
            get {
                return ResourceManager.GetString("PP_FloydWpfMedianCut_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum iterations for Gaussian mixture model. Integer. Recommended 10~50. Lower values are faster but may not converge, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_GMMMaxIter_ToolTip {
            get {
                return ResourceManager.GetString("PP_GMMMaxIter_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 2000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_GMMMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_GMMMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grayscale Palette 的本地化字符串。
        /// </summary>
        public static string PP_GrayPalette {
            get {
                return ResourceManager.GetString("PP_GrayPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color count is 2 to the power of bit depth, but each color is a grayscale value. 的本地化字符串。
        /// </summary>
        public static string PP_GrayPalette_ToolTip {
            get {
                return ResourceManager.GetString("PP_GrayPalette_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum pixel samples for hierarchical clustering. Integer. Recommended 350. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_HierarchicalMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_HierarchicalMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Iterations (iterations) 的本地化字符串。
        /// </summary>
        public static string PP_Iterations {
            get {
                return ResourceManager.GetString("PP_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of KMeans clustering iterations. Integer. Recommended 5~20. Lower values are faster but less accurate, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_Iterations_ToolTip {
            get {
                return ResourceManager.GetString("PP_Iterations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans Iterations (kmeansIters) 的本地化字符串。
        /// </summary>
        public static string PP_KMeansIters {
            get {
                return ResourceManager.GetString("PP_KMeansIters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of KMeans clustering iterations. Integer. Recommended 3~10. Lower values are faster but less accurate, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_KMeansIters_ToolTip {
            get {
                return ResourceManager.GetString("PP_KMeansIters_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans Iterations 的本地化字符串。
        /// </summary>
        public static string PP_KMeansIters2 {
            get {
                return ResourceManager.GetString("PP_KMeansIters2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans++ 的本地化字符串。
        /// </summary>
        public static string PP_KMeansPP {
            get {
                return ResourceManager.GetString("PP_KMeansPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum KMeans iterations. Integer. Recommended 50~200. Lower values may not converge, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_LabKMeansMaxIterations_ToolTip {
            get {
                return ResourceManager.GetString("PP_LabKMeansMaxIterations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence threshold for clustering. Decimal. Recommended 0.1~5. Lower values are more accurate but slower, higher values are faster but less precise. 的本地化字符串。
        /// </summary>
        public static string PP_LabKMeansThreshold_ToolTip {
            get {
                return ResourceManager.GetString("PP_LabKMeansThreshold_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linkage Method (linkage) 的本地化字符串。
        /// </summary>
        public static string PP_Linkage {
            get {
                return ResourceManager.GetString("PP_Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Linkage method for hierarchical clustering. Single linkage: prone to long chains, noise sensitive; Complete linkage: compact clusters, noise resistant; Average linkage: compromise. 的本地化字符串。
        /// </summary>
        public static string PP_Linkage_ToolTip {
            get {
                return ResourceManager.GetString("PP_Linkage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manhattan Distance 的本地化字符串。
        /// </summary>
        public static string PP_ManhattanDistance {
            get {
                return ResourceManager.GetString("PP_ManhattanDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Suitable for discrete data. 的本地化字符串。
        /// </summary>
        public static string PP_ManhattanDistance_ToolTip {
            get {
                return ResourceManager.GetString("PP_ManhattanDistance_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bayer Matrix Size 的本地化字符串。
        /// </summary>
        public static string PP_MatrixSize {
            get {
                return ResourceManager.GetString("PP_MatrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size of Bayer matrix. 2x2: large dither grain, 4x4: commonly used, 8x8: fine grain but may lose details. 的本地化字符串。
        /// </summary>
        public static string PP_MatrixSize_ToolTip {
            get {
                return ResourceManager.GetString("PP_MatrixSize_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Iterations (maxIter) 的本地化字符串。
        /// </summary>
        public static string PP_MaxIter {
            get {
                return ResourceManager.GetString("PP_MaxIter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Iterations (maxIterations) 的本地化字符串。
        /// </summary>
        public static string PP_MaxIterations {
            get {
                return ResourceManager.GetString("PP_MaxIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum KMeans iterations. Integer. Recommended 50~200. Lower values may not converge, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_MaxIterations_ToolTip {
            get {
                return ResourceManager.GetString("PP_MaxIterations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Level (maxLevel) 的本地化字符串。
        /// </summary>
        public static string PP_MaxLevel {
            get {
                return ResourceManager.GetString("PP_MaxLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum octree level. Integer. Recommended 6~8. Lower values are faster but with low color resolution, higher values are more detailed but slower. 的本地化字符串。
        /// </summary>
        public static string PP_MaxLevel_ToolTip {
            get {
                return ResourceManager.GetString("PP_MaxLevel_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max Samples (maxSamples) 的本地化字符串。
        /// </summary>
        public static string PP_MaxSamples {
            get {
                return ResourceManager.GetString("PP_MaxSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 20000~50000. Lower values are faster but less accurate, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_MaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_MaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum iterations for mean shift. Integer. Recommended 5~20. Lower values may not converge, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_MeanShiftMaxIter_ToolTip {
            get {
                return ResourceManager.GetString("PP_MeanShiftMaxIter_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 10000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_MeanShiftMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_MeanShiftMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min Points (minPts) 的本地化字符串。
        /// </summary>
        public static string PP_MinPts {
            get {
                return ResourceManager.GetString("PP_MinPts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum points for DBSCAN clustering. Integer. Recommended 3~10. Lower values make it easier to form small clusters, higher values make it harder to form clusters. 的本地化字符串。
        /// </summary>
        public static string PP_MinPts_ToolTip {
            get {
                return ResourceManager.GetString("PP_MinPts_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum pixel samples for octree. Integer. Recommended 20000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_OctreeMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_OctreeMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Neighborhood radius for OPTICS clustering. Decimal. Recommended 8~64. Lower values produce finer clustering, higher values produce coarser clustering. 的本地化字符串。
        /// </summary>
        public static string PP_OPTICSEpsilon_ToolTip {
            get {
                return ResourceManager.GetString("PP_OPTICSEpsilon_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 2000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_OPTICSMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_OPTICSMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimum points for OPTICS clustering. Integer. Recommended 3~10. Lower values make it easier to form small clusters, higher values make it harder to form clusters. 的本地化字符串。
        /// </summary>
        public static string PP_OPTICSMinPts_ToolTip {
            get {
                return ResourceManager.GetString("PP_OPTICSMinPts_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the algorithm for generating the base palette. Different algorithms affect color distribution and speed. 的本地化字符串。
        /// </summary>
        public static string PP_OrderedDitherBaseMethod_ToolTip {
            get {
                return ResourceManager.GetString("PP_OrderedDitherBaseMethod_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dither error diffusion strength. Decimal. Recommended 1.0. Lower values produce weaker dithering, higher values produce stronger dithering, too high may cause excessive noise. 的本地化字符串。
        /// </summary>
        public static string PP_OrderedDitherStrength_ToolTip {
            get {
                return ResourceManager.GetString("PP_OrderedDitherStrength_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PCA Principal Component 的本地化字符串。
        /// </summary>
        public static string PP_PCA {
            get {
                return ResourceManager.GetString("PP_PCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum pixel samples for PCA. Integer. Recommended 20000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_PcaMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_PcaMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Power Iterations (power iterations) 的本地化字符串。
        /// </summary>
        public static string PP_PowerIterations {
            get {
                return ResourceManager.GetString("PP_PowerIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Number of power iterations for PCA principal component analysis. Integer. Recommended 10~30. Lower values are faster but less accurate principal components, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_PowerIterations_ToolTip {
            get {
                return ResourceManager.GetString("PP_PowerIterations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence Rate (rate) 的本地化字符串。
        /// </summary>
        public static string PP_Rate {
            get {
                return ResourceManager.GetString("PP_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence rate for KMeans clustering. Decimal. Recommended 0.1~0.5. Lower values converge slower but more stable, higher values converge faster but may be unstable. 的本地化字符串。
        /// </summary>
        public static string PP_Rate_ToolTip {
            get {
                return ResourceManager.GetString("PP_Rate_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random Seed (seed) 的本地化字符串。
        /// </summary>
        public static string PP_Seed {
            get {
                return ResourceManager.GetString("PP_Seed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Random seed for clustering initialization. Integer. 0 for automatic random, other values can reproduce results. 的本地化字符串。
        /// </summary>
        public static string PP_Seed_ToolTip {
            get {
                return ResourceManager.GetString("PP_Seed_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serpentine Scan 的本地化字符串。
        /// </summary>
        public static string PP_Serpentine {
            get {
                return ResourceManager.GetString("PP_Serpentine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaussian Kernel σ (sigma) 的本地化字符串。
        /// </summary>
        public static string PP_Sigma {
            get {
                return ResourceManager.GetString("PP_Sigma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaussian kernel σ for spectral clustering. Decimal. Recommended 16~64. Lower values produce finer clustering, higher values produce coarser clustering. 的本地化字符串。
        /// </summary>
        public static string PP_Sigma_ToolTip {
            get {
                return ResourceManager.GetString("PP_Sigma_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Single Linkage 的本地化字符串。
        /// </summary>
        public static string PP_SingleLinkage {
            get {
                return ResourceManager.GetString("PP_SingleLinkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merges closest clusters each time, prone to long chains, noise sensitive. 的本地化字符串。
        /// </summary>
        public static string PP_SingleLinkage_ToolTip {
            get {
                return ResourceManager.GetString("PP_SingleLinkage_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2x2 的本地化字符串。
        /// </summary>
        public static string PP_Size2x2 {
            get {
                return ResourceManager.GetString("PP_Size2x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large grain, suitable for special styles. 的本地化字符串。
        /// </summary>
        public static string PP_Size2x2_ToolTip {
            get {
                return ResourceManager.GetString("PP_Size2x2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4x4 的本地化字符串。
        /// </summary>
        public static string PP_Size4x4 {
            get {
                return ResourceManager.GetString("PP_Size4x4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commonly used, balances fineness and speed. 的本地化字符串。
        /// </summary>
        public static string PP_Size4x4_ToolTip {
            get {
                return ResourceManager.GetString("PP_Size4x4_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8x8 的本地化字符串。
        /// </summary>
        public static string PP_Size8x8 {
            get {
                return ResourceManager.GetString("PP_Size8x8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fine grain but may lose details. 的本地化字符串。
        /// </summary>
        public static string PP_Size8x8_ToolTip {
            get {
                return ResourceManager.GetString("PP_Size8x8_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KMeans iterations after spectral clustering. Integer. Recommended 5~20. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_SpectralKMeansIters_ToolTip {
            get {
                return ResourceManager.GetString("PP_SpectralKMeansIters_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum pixel samples for spectral clustering. Integer. Recommended 2000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_SpectralMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_SpectralMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence Threshold (threshold) 的本地化字符串。
        /// </summary>
        public static string PP_Threshold {
            get {
                return ResourceManager.GetString("PP_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence threshold for clustering. Decimal. Recommended 0.1~5. Lower values are more accurate but slower, higher values are faster but less precise. 的本地化字符串。
        /// </summary>
        public static string PP_Threshold_ToolTip {
            get {
                return ResourceManager.GetString("PP_Threshold_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence Threshold (tol) 的本地化字符串。
        /// </summary>
        public static string PP_Tol {
            get {
                return ResourceManager.GetString("PP_Tol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convergence threshold for Gaussian mixture model. Decimal. Recommended 0.1~5. Lower values are more accurate but slower, higher values are faster but less precise. 的本地化字符串。
        /// </summary>
        public static string PP_Tol_ToolTip {
            get {
                return ResourceManager.GetString("PP_Tol_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 20000. Lower values are faster but less accurate, higher values are more accurate but slower. 的本地化字符串。
        /// </summary>
        public static string PP_VarianceSplitMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_VarianceSplitMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum number of pixel samples for clustering. Integer. Recommended 20000. Lower values are faster but less accurate, higher values are slower but more accurate. 的本地化字符串。
        /// </summary>
        public static string PP_WeightedMaxMinMaxSamples_ToolTip {
            get {
                return ResourceManager.GetString("PP_WeightedMaxMinMaxSamples_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF+KMeans 的本地化字符串。
        /// </summary>
        public static string PP_WpfKMeans {
            get {
                return ResourceManager.GetString("PP_WpfKMeans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WPF Median Cut 的本地化字符串。
        /// </summary>
        public static string PP_WpfMedianCut {
            get {
                return ResourceManager.GetString("PP_WpfMedianCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please Wait... 的本地化字符串。
        /// </summary>
        public static string PreviewTip {
            get {
                return ResourceManager.GetString("PreviewTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Colors 的本地化字符串。
        /// </summary>
        public static string RawMidiSelect {
            get {
                return ResourceManager.GetString("RawMidiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Area Resampling 的本地化字符串。
        /// </summary>
        public static string RM_AreaResampling {
            get {
                return ResourceManager.GetString("RM_AreaResampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bicubic 的本地化字符串。
        /// </summary>
        public static string RM_Bicubic {
            get {
                return ResourceManager.GetString("RM_Bicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bilinear 的本地化字符串。
        /// </summary>
        public static string RM_Bilinear {
            get {
                return ResourceManager.GetString("RM_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Box Filter 的本地化字符串。
        /// </summary>
        public static string RM_BoxFilter {
            get {
                return ResourceManager.GetString("RM_BoxFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaussian 的本地化字符串。
        /// </summary>
        public static string RM_Gaussian {
            get {
                return ResourceManager.GetString("RM_Gaussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hermite 的本地化字符串。
        /// </summary>
        public static string RM_Hermite {
            get {
                return ResourceManager.GetString("RM_Hermite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Integal Image 的本地化字符串。
        /// </summary>
        public static string RM_IntegralImage {
            get {
                return ResourceManager.GetString("RM_IntegralImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lanczos 的本地化字符串。
        /// </summary>
        public static string RM_Lanczos {
            get {
                return ResourceManager.GetString("RM_Lanczos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mitchell 的本地化字符串。
        /// </summary>
        public static string RM_Mitchell {
            get {
                return ResourceManager.GetString("RM_Mitchell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModePooling 的本地化字符串。
        /// </summary>
        public static string RM_ModePooling {
            get {
                return ResourceManager.GetString("RM_ModePooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nearest Neighbor 的本地化字符串。
        /// </summary>
        public static string RM_NearestNeighbor {
            get {
                return ResourceManager.GetString("RM_NearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export MIDI 的本地化字符串。
        /// </summary>
        public static string SaveMidi {
            get {
                return ResourceManager.GetString("SaveMidi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set 的本地化字符串。
        /// </summary>
        public static string SetHexButton {
            get {
                return ResourceManager.GetString("SetHexButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string SettingsSelect {
            get {
                return ResourceManager.GetString("SettingsSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Offset 的本地化字符串。
        /// </summary>
        public static string StartOffset {
            get {
                return ResourceManager.GetString("StartOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ticks per Pixel 的本地化字符串。
        /// </summary>
        public static string TicksPerPixel {
            get {
                return ResourceManager.GetString("TicksPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image To MIDI Modded v1.4.5 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toolbox 的本地化字符串。
        /// </summary>
        public static string Toolbox {
            get {
                return ResourceManager.GetString("Toolbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use Grayscale Image 的本地化字符串。
        /// </summary>
        public static string UseGrayscaleImage {
            get {
                return ResourceManager.GetString("UseGrayscaleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector Image Preview Width 的本地化字符串。
        /// </summary>
        public static string VectorImagePreviewWidth {
            get {
                return ResourceManager.GetString("VectorImagePreviewWidth", resourceCulture);
            }
        }
    }
}
